#!/bin/bash
# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
source ~/env/bin/activate
while true; do
    sudo timedatectl set-timezone UTC > /dev/null 2>&1

    # Display menu
    echo -e "${YELLOW}🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛${NC}"
    echo "******************************************" 
    echo "   -pxy                   🔘        🔥"
    echo "   -pyp                   🎉        pp"
    echo "   -pxypy                 🐍        py"
    echo "   -pxytp                 🚛        tp"
    echo "   -pxybuy                🌱        by"
    echo "   -pxypnl                💰        pl"
    echo "   -pxyopt                🛸        op"
    echo "   -pxyclean              🚿        cl"
    echo "   -pxycheck              🧪        ck"
    echo "   -pxyupdate             📥        up"
    echo "******************************************"
    echo -e "${YELLOW}🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛${NC}"

    # Get user input
    read -p "Enter your choice:⚙️⚙️⚙️👉👉 " choice

    # Perform actions based on user input
    case $choice in

        pp)
            echo "    🎉🎉🎉.pip install.🎉🎉🎉"
            pyp
            ;;   
        pl)
            echo "    💰💰💰.pip install.💰💰💰"
            pxypnl
            ;;           
        tp)
            echo "    🚛🚛.pxycloudsynch.🚛🚛"
            pxytp
            ;;           
        by)
            echo "    🌱🌱🌱..Buy Now.🌱🌱🌱"
            pxybuy
            ;;   
        op)
            echo "    🛸🛸🛸..Opt Now..🛸🛸🛸"
            pxyopt
            ;;           
        up)
            echo "   🧰⚙️🔧🛠️🔐 Update PXY®...🧰⚙️🔧🛠️🔐"
            pxyupdate
            ;;
        cl)
            echo "    🚿🚿🚿 Cleanup..🚿🚿🚿"
            pxyclean
            ;;
        ck)
            echo "    🧪🧪🧪 Test All PXY®...🧪🧪🧪"
            pxycheck
            ;;
        py)
            echo "    ...................👉exe/run"
            pxypy
            ;;

        py)
            echo "    💻💻💻💻..👉exe/run"
            py
            ;;
        "")
            echo ".........Lets have fun with PXY®  🔥💫🚀🔥"
            pxypxy
            ;;
        en)
            echo ".........Lets have fun with PXY®  🔥💫🚀🔥"
            pxypxy
            ;;
        *)
            # Handle other cases if needed
            echo "Invalid choice: $choice"
            ;;
    esac
done

