#!/bin/bash
# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
source ~/env/bin/activate
while true; do
    # Display menu
    echo -e "${YELLOW}🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛${NC}"
    echo "******************************************" 
    echo "   -pxy                   🔘        🔥"
    echo "   -pyp                   🎉        pp"
    echo "   -pxypy                 🐍        py"
    echo "   -pxytp                 🚛        tp"
    echo "   -pxybuy                🌱        by"
    echo "   -pxyopt                🛸        op"
    echo "   -pxytail               📜        ta"
    echo "   -pxyauto               🤖        at"
    echo "   -pxytest               🧩        ts"
    echo "   -pxyclean              🚿        cl"
    echo "   -pxyflush              💨        fl"    
    echo "   -pxycheck              🧪        ck"
    echo "   -pxyupdate             📥        up"
    echo "******************************************"
    echo -e "${YELLOW}🏛🏛 PXY® PreciseXceleratedYield Pvt Ltd™ 🏛🏛${NC}"

    # Get user input
    read -p "Enter your choice:⚙️⚙️⚙️👉👉 " choice

    # Perform actions based on user input
    case $choice in

        pp)
            echo "    🎉🎉🎉.pip install.🎉🎉🎉"
            pyp
            ;;   
        tp)
            echo "    🚛🚛.pxycloudsynch.🚛🚛"
            pxytp
            ;;           
        by)
            echo "    🌱🌱🌱..Buy Now.🌱🌱🌱"
            pxybuy
            ;;   
        op)
            echo "    🛸🛸🛸..Opt Now..🛸🛸🛸"
            pxyopt
            ;;           
        ts)
            echo "    🧑‍💻🧑‍💻🧑‍💻.Test txy.🧑‍💻🧑‍💻🧑‍💻"
            pxytest
            ;;   
        at)
            echo "    🤖🤖.Options Auto.🤖🤖"
            pxyauto
            ;; 
        ta)
            echo "    📜📜📜.tailing logs.📜📜📜"
            pxytail
            ;; 
        fl)
            echo "...............flush put💨💨💨"
            pxyflush
            ;;    

        up)
            echo "   🧰⚙️🔧🛠️🔐 Update PXY®...🧰⚙️🔧🛠️🔐"
            pxyupdate
            ;;
        cl)
            echo "    🚿🚿🚿 Cleanup..🚿🚿🚿"
            pxyclean
            ;;
        ck)
            echo "    🧪🧪🧪 Test All PXY®...🧪🧪🧪"
            pxycheck
            ;;
        py)
            echo "    ...................👉exe/run"
            pxypy
            ;;

        py)
            echo "    💻💻💻💻..👉exe/run"
            py
            ;;

        "")
            echo "...Lets have fun with PXY®  🔥💫🚀🔥"
            pxypxy
            ;;
        en)
            echo "...Lets have fun with PXY®  🔥💫🚀🔥"
            pxypxy
            ;;
        *)
            # Handle other cases if needed
            echo "Invalid choice: $choice"
            ;;
    esac
done

