#!/bin/bash

# Activate the virtual environment
source ~/env/bin/activate

# Change to the script's directory
cd ~/pxy/sys/exe/run
echo "__________________________________________"
echo "buy,dsh,cln,cntrl,kill,bukd,idocln,minus,plus,fund,mkt,nft,sell,time,loop,swch,ord,prft,smb"
echo "__________________________________________"
read -p "Enter your script name: " script_name

# Run the Python script with the user-provided input
python3 "${script_name}pxy.py"
