#!/bin/bash

# Change to the directory
cd ~/pxy/sys/exe/run

# Activate the virtual environment
source ~/env/bin/activate

# Check if the .py or .pcy file exists and run it
if [ -f "pycpxy.py" ]; then
    python3 pycpxy.py
elif [ -f "pycpxy.pcy" ]; then
    python3 pycpxy.pcy
else
    echo "Error: Neither pxypyc.py nor pxypyc.pcy found in /home/pxy/pxy/sys/exe/run/"
    exit 1
fi

# Display summary at the end
# (Add commands here to display your summary, if any)
