#!/bin/bash

rclone sync --progress --verbose --config=.config/rclone/rclone.conf /home/userland/pxy/sys/exe/run/fileHPdf.csv /home/userland/pxy/sys/exe/run/filePnL.csv /home/userland/pxy/sys/exe/run/filePnL_nrml.csv /home/userland/pxy/sys/exe/run/mempxy.csv pxycloud:/csv