#!/bin/bash

rclone sync --progress --verbose --config=.config/rclone/rclone.conf ~/pxy/sys/exe/run/filePnL.csv pxycloud:/csv
rclone sync --progress --verbose --config=.config/rclone/rclone.conf ~/pxy/sys/exe/run/filePnL_nrml.csv pxycloud:/csv
rclone sync --progress --verbose --config=.config/rclone/rclone.conf ~/pxy/sys/exe/run/mempxy.csv pxycloud:/csv
