#!/bin/bash

while true; do
    clear
    echo "Menu:"
    echo "1. 🌐 Set timezone and update time"
    echo "2. 🚀 Add user to sudo group"
    echo "3. 🔄 Update system packages"
    echo "4. 🐍 Install Python 3.9 and env"
    echo "5. 🐙 Install Git and clone a repository"
    echo "6. 🛠️ Install requirements"
    echo "7. ❌ Exit"

    read -p "Enter your choice (1-6): " choice

    case $choice in
        1)
            sudo timedatectl set-timezone UTC && sudo timedatectl set-local-rtc 0 && timedatectl
            ;;
        2)
            sudo usermod -aG sudo pxy
            sudo usermod -aG sudo userland
            ;;
        3)
            sudo apt update
            sudo apt install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt update
            ;;
        4)
            sudo apt install python3.9
            python3.9 --version
            sudo apt install python3.9-venv
            python3.9 -m venv env
            sudo chmod -R 777 env
            source ~/env/bin/activate
            pip install --upgrade pip
            ;;
        5)
            sudo apt install git
            git --version
            git clone https://github.com/kcbpcc/pxy.git
            sudo chmod -R 777 pxy
            sudo cp ~/pxy/sys/pxy* /usr/local/bin/
            sudo chmod +x /usr/local/bin/pxy*
            ;;

        6)            
            cd ~/pxy/sys/exe
            sudo pip install -r requirements.txt
            cd ~/pxy/sys/exe/run
            ;;

        7)
            echo "❌ Exiting script. Goodbye! ❌"
            exit 0
            ;;
        *)
            echo "❗ Invalid choice. Please enter a number between 1 and 6. ❗"
            ;;
    esac

    read -p "Press Enter to continue..."
done
