#!/bin/bash

echo "Menu:"
echo "1. Export"
echo "2. Import"
read -p "Choose an option (export/import): " option

# ANSI escape codes for colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'  # No Color

case $option in
    export)
        # Export
        echo "Exporting files to pxycloud:/csv"
        for file in filePnL.csv filePnL_nrml.csv mempxy.csv bordpxy.csv acvalue.csv
        do
            read -p "Do you want to export $file? (y/n): " confirm_export
            case $confirm_export in
                [Yy])
                    rclone copy --ignore-times --progress --verbose --config=.config/rclone/rclone.conf ~/pxy/sys/exe/run/$file pxycloud:/csv/
                    sudo chmod 777 ~/pxy/sys/exe/run/ -R
                    echo -e "${GREEN}Exported $file${NC}"
                    ;;
                [Nn])
                    echo -e "${RED}Skipped $file${NC}"
                    ;;
                *)
                    echo "Invalid input. Please enter 'y' or 'n'."
                    ;;
            esac
        done
        echo "Export completed."
        ;;

    import)
        # Import
        echo "Importing files from pxycloud:/csv"
        for file in filePnL.csv filePnL_nrml.csv mempxy.csv bordpxy.csv acvalue.csv
        do
            read -p "Do you want to import $file? (y/n): " confirm_import
            case $confirm_import in
                [Yy])
                    rclone copy --ignore-times --progress --verbose --config=.config/rclone/rclone.conf pxycloud:/csv/$file ~/pxy/sys/exe/run/
                    sudo chmod 777 ~/pxy/sys/exe/run/ -R
                    echo -e "${GREEN}Imported $file${NC}"
                    ;;
                [Nn])
                    echo -e "${RED}Skipped $file${NC}"
                    ;;
                *)
                    echo "Invalid input. Please enter 'y' or 'n'."
                    ;;
            esac
        done
        echo "Import completed."
        ;;

    *)
        echo "Invalid option. Please choose 'export' or 'import'."
        exit 1
        ;;
esac

