#!/bin/bash

LOG_FILE=~/pxy/sys/exe/main.log

# Check if the log file exists
if [ ! -f "$LOG_FILE" ]; then
    echo "Error: Log file $LOG_FILE not found."
    exit 1
fi

# Continuously display the last 10 lines of the main log file
tail -n 10 -f "$LOG_FILE"