#!/bin/bash
cd $HOME/pxy
mv /home/userland/pxy/sys/exe/run/filePnL.csv /home/userland/pxy/sys/exe/run/_filePnL.csv 
echo '                                 '
echo "       *****GET UPDATES**********"
echo '                                 '
git fetch --all
echo '                                 '
echo "       *****RESET SOFTWERE*******"
echo '                                 '
git reset --hard origin/main
sudo cp ~/pxy/sys/* /usr/local/bin/ &> /dev/null
sudo chmod +x /usr/local/bin/*
echo '                                 '
echo "       *****UPDATE COMPLETED*****"
echo '                                 '
rm /home/userland/pxy/sys/exe/run/filePnL.csv
mv /home/userland/pxy/sys/exe/run/_filePnL.csv /home/userland/pxy/sys/exe/run/filePnL.csv 
