#!/bin/bash

dir=$HOME/pxy/sys/exe/run

# Move all CSV files to their temporary versions
for file in $dir/*.csv; do
    mv "$file" "$dir/$(basename "$file" .csv)_temp.csv"
done

echo '                                 '
echo "       ******** GET UPDATES *******"
echo '                                 '
git fetch --all
echo '                                 '
echo "       ****** RESET SOFTWARE ******"
echo '                                 '
git reset --hard origin/main
sudo cp ~/pxy/sys/pxy ~/pxy/sys/p
sudo cp ~/pxy/sys/* /usr/local/bin/ &> /dev/null
sudo chmod +x /usr/local/bin/*
echo '                                 '
echo "       ***** UPDATE COMPLETED *****"
echo '                                 '

# Move back the temporary versions to their original names
for file in $dir/*_temp.csv; do
    mv "$file" "$dir/$(basename "$file" _temp.csv).csv"
done
