#!/bin/bash
cd $HOME/pxy
#mv $HOME/pxy/sys/exe/run/filePnL.csv $HOME/pxy/sys/exe/run/_filePnL.csv 
#mv $HOME/pxy/sys/exe/run/filePnL_nrml.csv $HOME/pxy/sys/exe/run/_filePnL_nrml.csv 
echo '                                 '
echo "       ******** GET UPDATES *******"
echo '                                 '
git fetch --all
echo '                                 '
echo "       ****** RESET SOFTWERE ******"
echo '                                 '
git reset --hard origin/main
sudo cp ~/pxy/sys/pxy ~/pxy/sys/p
sudo cp ~/pxy/sys/* /usr/local/bin/ &> /dev/null
sudo chmod +x /usr/local/bin/*
echo '                                 '
echo "       ***** UPDATE COMPLETED *****"
echo '                                 '
pxypyc
#rm $HOME/pxy/sys/exe/run/filePnL.csv
#mv $HOME/pxy/sys/exe/run/_filePnL.csv $HOME/pxy/sys/exe/run/filePnL.csv 
#mv $HOME/pxy/sys/exe/run/_filePnL_nrml.csv $HOME/pxy/sys/exe/run/filePnL_nrml.csv
