#!/bin/bash

# Define the URLs
declare -A urls=(
    ["prf"]="https://console.zerodha.com/verified/ba914521"
    ["set"]="https://trendlyne.com/fundamentals/your-parameters/updated-desc-param/"
    ["chr"]="https://www.tradingview.com/chart/bmZV8D16/?symbol=NSE%3ANIFTY"
    ["gpt"]="https://chat.openai.com/c/e1857754-dbaf-4ada-a0c9-2d97ce22177d"
    ["git"]="https://github.com/PreciseXceleratedYieldPXY/PXY"
)

# Display the menu
echo "Menu:"
for key in "${!urls[@]}"; do
    echo "Press '$key' for ${urls[$key]}"
done

# Function to open URL based on key
open_url() {
    key=$1
    url=${urls[$key]}

    if [ -n "$url" ]; then
        if command -v open &> /dev/null; then
            open "$url"  # macOS
        elif command -v xdg-open &> /dev/null; then
            xdg-open "$url"  # Linux
        else
            echo "Error: Unable to open URL. Please open it manually in your web browser."
        fi
    else
        echo "Invalid key. Please choose a valid key."
    fi
}

# Prompt user for input
read -p "Enter the key to open the corresponding link: " user_input
open_url "$user_input"
