#!/bin/bash

# Ask the user for input
read -p "Enter the package name to install: " packageName

# Execute the commands
cd ~/pxy/sys/exe/run && source ~/env/bin/activate && pip install "$packageName"

