#!/bin/bash

echo "Menu:"
echo "1. Export"
echo "2. Import"
read -p "Choose an option (export/import): " option

# ANSI escape codes for colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'  # No Color

files_to_process=("filePnL.csv" "filePnL_nrml.csv" "mempxy.csv" "bordpxy.csv" "acvalue.csv" "empty.csv")

case $option in
    exp)
        # Export
        echo "Exporting files to pxycloud:/csv"
        read -p "Do you want to export all files? (y/n): " confirm_export_all
        if [ "$confirm_export_all" == "y" ]; then
            for file in "${files_to_process[@]}"; do
                if rclone copy --ignore-times --progress --verbose --config=.config/rclone/rclone.conf ~/pxy/sys/exe/run/"$file" pxycloud:/csv/; then
                    sudo chmod 777 ~/pxy/sys/exe/run/ -R
                    echo -e "${GREEN}Exported $file${NC}"
                else
                    echo -e "${RED}Error exporting $file${NC}"
                fi
            done
            echo "Export completed."
        else
            echo -e "${RED}Export operation canceled.${NC}"
        fi
        ;;

    imp)
        # Import
        echo "Importing files from pxycloud:/csv"
        read -p "Do you want to import all files? (y/n): " confirm_import_all
        if [ "$confirm_import_all" == "y" ]; then
            for file in "${files_to_process[@]}"; do
                if rclone copy --ignore-times --progress --verbose --config=.config/rclone/rclone.conf pxycloud:/csv/"$file" ~/pxy/sys/exe/run/; then
                    sudo chmod 777 ~/pxy/sys/exe/run/ -R
                    echo -e "${GREEN}Imported $file${NC}"
                else
                    echo -e "${RED}Error importing $file${NC}"
                fi
            done
            echo "Import completed."
        else
            echo -e "${RED}Import operation canceled.${NC}"
        fi
        ;;

    *)
        echo "Invalid option. Please choose 'export' or 'import'."
        exit 1
        ;;
esac





